CORCI_HOST=${SERVER_HOST:-${CORCI_PORT_8080_TCP_ADDR}}
CORCI_PORT=${SERVER_PORT:-${CORCI_PORT_8080_TCP_PORT}}
CORCI_PROTOCOL=${SERVER_PROTOCOL:-${CORCI_ENV_CORCI_PROTOCOL}}

echo Connecting to ${CORCI_PROTCOL}://${CORCI_HOST}:${CORCI_PORT}...

corci-android -h ${CORCI_HOST} -p ${CORCI_PORT} -q ${CORCI_PROTOCOL} -l /builds -n ${CORCI_NAME}